# Generated by Django 5.0.3 on 2024-03-17 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('красный', 'красный'), ('синий', 'синий'), ('желтый', 'желтый'), ('зеленый', 'зеленый')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('очень важно', 'очень важно'), ('важно', 'важно'), ('желательно', 'желательно'), ('мечтаю', 'мечтаю')], max_length=20)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tagmodel')),
            ],
        ),
    ]
